<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="14" time="1.995" timestamp="2024-09-09T17:11:57.974695" hostname="DESKTOP-HP3M6LC"><testcase classname="tests.fixtures.test_fixtures" name="test_addFeature" file="tests\fixtures\test_fixtures.py" line="32" time="0.281"><failure message="TypeError: 'NoneType' object is not subscriptable">projectModel = &lt;Models.ProjectModel.ProjectModel object at 0x000002887E05FA90&gt;
populateDatabase = {'feature': None, 'issue': None, 'project': {'dateCreated': '01-01-2014', 'projectDescription': 'A test description', 'projectId': 1, 'projectName': 'Test Project'}, 'task': None}

    def test_addFeature(projectModel, populateDatabase):
    
&gt;       task = projectModel.getTask(populateDatabase["task"]["taskId"])
E       TypeError: 'NoneType' object is not subscriptable

tests\fixtures\test_fixtures.py:35: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'

</system-err></testcase><testcase classname="tests.fixtures.test_fixtures" name="test_addIssue" file="tests\fixtures\test_fixtures.py" line="47" time="0.113"><failure message="TypeError: 'NoneType' object is not subscriptable">projectModel = &lt;Models.ProjectModel.ProjectModel object at 0x000002887E315420&gt;
populateDatabase = {'feature': None, 'issue': None, 'project': {'dateCreated': '01-01-2014', 'projectDescription': 'A test description', 'projectId': 1, 'projectName': 'Test Project'}, 'task': None}

    def test_addIssue(projectModel, populateDatabase):
    
&gt;       issue = projectModel.getIssue(populateDatabase["issue"]["issueId"])
E       TypeError: 'NoneType' object is not subscriptable

tests\fixtures\test_fixtures.py:50: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'

</system-err></testcase><testcase classname="tests.fixtures.test_fixtures" name="test_addProject" file="tests\fixtures\test_fixtures.py" line="7" time="0.110"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| 'getProject'

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteFeature" file="tests\models\test_projectModel.py" line="31" time="0.138"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:33 in test_deleteFeature() at 17:11:58.664

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteIssue" file="tests\models\test_projectModel.py" line="55" time="0.133"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:57 in test_deleteIssue() at 17:11:58.798

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteProject" file="tests\models\test_projectModel.py" line="19" time="0.133"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:21 in test_deleteProject() at 17:11:58.932

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteTask" file="tests\models\test_projectModel.py" line="43" time="0.126"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:45 in test_deleteTask() at 17:11:59.057

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_getProjectName" file="tests\models\test_projectModel.py" line="6" time="0.163"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:8 in test_getProjectName() at 17:11:59.222

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateFeature" file="tests\models\test_projectModel.py" line="25" time="0.170"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:27 in test_updateFeature() at 17:11:59.392

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateIssue" file="tests\models\test_projectModel.py" line="49" time="0.306"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:51 in test_updateIssue() at 17:11:59.699

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateProject" file="tests\models\test_projectModel.py" line="13" time="0.098"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:15 in test_updateProject() at 17:11:59.798

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateTask" file="tests\models\test_projectModel.py" line="37" time="0.129"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:39 in test_updateTask() at 17:11:59.928

</system-err></testcase><testcase classname="tests.views.test_aboutView" name="test_init" file="tests\views\test_aboutView.py" line="21" time="0.034"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.views.test_aboutView" name="test_signals" file="tests\views\test_aboutView.py" line="40" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>