<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="3" skipped="0" tests="15" time="2.289" timestamp="2024-09-10T01:16:42.634528" hostname="DESKTOP-HP3M6LC"><testcase classname="tests.fixtures.test_fixtures" name="test_addFeature" file="tests\fixtures\test_fixtures.py" line="19" time="0.287"><failure message="TypeError: 'NoneType' object is not subscriptable">projectModel = &lt;Models.ProjectModel.ProjectModel object at 0x0000028F9C053F40&gt;
populateDatabase = {'feature': None, 'issue': None, 'project': {'dateCreated': '01-01-2014', 'projectDescription': 'A test description', 'projectId': 1, 'projectName': 'Test Project'}, 'task': None}

    def test_addFeature(projectModel, populateDatabase):
    
&gt;       feature = projectModel.getFeature(populateDatabase["feature"]["featureId"])
E       TypeError: 'NoneType' object is not subscriptable

tests\fixtures\test_fixtures.py:22: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'

</system-err></testcase><testcase classname="tests.fixtures.test_fixtures" name="test_addIssue" file="tests\fixtures\test_fixtures.py" line="47" time="0.109"><failure message="TypeError: 'NoneType' object is not subscriptable">projectModel = &lt;Models.ProjectModel.ProjectModel object at 0x0000028F9C306290&gt;
populateDatabase = {'feature': None, 'issue': None, 'project': {'dateCreated': '01-01-2014', 'projectDescription': 'A test description', 'projectId': 1, 'projectName': 'Test Project'}, 'task': None}

    def test_addIssue(projectModel, populateDatabase):
    
&gt;       issue = projectModel.getIssue(populateDatabase["issue"]["issueId"])
E       TypeError: 'NoneType' object is not subscriptable

tests\fixtures\test_fixtures.py:50: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'

</system-err></testcase><testcase classname="tests.fixtures.test_fixtures" name="test_addProject" file="tests\fixtures\test_fixtures.py" line="7" time="0.142"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| 'getProject'

</system-err></testcase><testcase classname="tests.fixtures.test_fixtures" name="test_addTask" file="tests\fixtures\test_fixtures.py" line="32" time="0.128"><failure message="TypeError: 'NoneType' object is not subscriptable">projectModel = &lt;Models.ProjectModel.ProjectModel object at 0x0000028F9C313B80&gt;
populateDatabase = {'feature': None, 'issue': None, 'project': {'dateCreated': '01-01-2014', 'projectDescription': 'A test description', 'projectId': 1, 'projectName': 'Test Project'}, 'task': None}

    def test_addTask(projectModel, populateDatabase):
    
&gt;       task = projectModel.getTask(populateDatabase["task"]["taskId"])
E       TypeError: 'NoneType' object is not subscriptable

tests\fixtures\test_fixtures.py:35: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteFeature" file="tests\models\test_projectModel.py" line="31" time="0.134"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:33 in test_deleteFeature() at 01:16:43.507

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteIssue" file="tests\models\test_projectModel.py" line="55" time="0.165"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:57 in test_deleteIssue() at 01:16:43.673

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteProject" file="tests\models\test_projectModel.py" line="19" time="0.171"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:21 in test_deleteProject() at 01:16:43.844

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_deleteTask" file="tests\models\test_projectModel.py" line="43" time="0.150"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:45 in test_deleteTask() at 01:16:43.994

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_getProjectName" file="tests\models\test_projectModel.py" line="6" time="0.160"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:8 in test_getProjectName() at 01:16:44.155

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateFeature" file="tests\models\test_projectModel.py" line="25" time="0.337"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:27 in test_updateFeature() at 01:16:44.493

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateIssue" file="tests\models\test_projectModel.py" line="49" time="0.138"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:51 in test_updateIssue() at 01:16:44.631

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateProject" file="tests\models\test_projectModel.py" line="13" time="0.105"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:15 in test_updateProject() at 01:16:44.736

</system-err></testcase><testcase classname="tests.models.test_projectModel" name="test_updateTask" file="tests\models\test_projectModel.py" line="37" time="0.112"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
ic| f"PRAGMA foreign_keys setting during test: {setting}": 'PRAGMA foreign_keys setting during test: 0'
ic| 'ProjectModel init'
ic| f"An error occurred addNewFeature: {e}": ('An error occurred addNewFeature: CHECK constraint failed: priority IN(1, 2, '
                                              '3, 4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| f"An error occurred addNewTask: {e}": ('An error occurred addNewTask: CHECK constraint failed: priority IN(1, 2, 3, '
                                           '4, 5)')
ic| 'getProject'
ic| 'getProjects'
ic| 'getTasks'
ic| 'getIssues'
ic| test_projectModel.py:39 in test_updateTask() at 01:16:44.849

</system-err></testcase><testcase classname="tests.views.test_aboutView" name="test_init" file="tests\views\test_aboutView.py" line="21" time="0.066"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.views.test_aboutView" name="test_signals" file="tests\views\test_aboutView.py" line="40" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>